# https://medium.com/@okan.ardic/spring-cloud-microservices-part-2-integrating-api-gateway-80f95e2c25d9
spring:
  application:
    name: service-gateway
  main: 
    web-application-type: REACTIVE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: swiggy-service
          uri: lb://swiggy-service
          predicates:
            - Path=/swiggy/**
          filters:
            - AuthenticationFilter

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/**
   
server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

# https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/actuator-api.html
# http://localhost:8080/actuator/gateway/routes
management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: 'gateway'
        
  # Micrometer  configuration 
  tracing:
    sampling:
      probability: 1.0 # only for testing purpose, switch back to 0.1 for production code
    propagation:
      type: b3
  # Zipkin  configuration 
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]' # Add ServiceName, TraceId and SpanId to logs