spring:
  application:
    name: question-service
    
server:
  port: 8093

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/