spring:
  application:
    name: quiz-service
    
server:
  port: 8094

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/